# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Fisher Ankney
tagline:          Outdoorsman
description:      Outdoorsman
#baseurl:          https://fisherankney.com
permalink:        /:title
author:
  name:           'Fisher Ankney'
url: https://fisherankney.com


# paginate:         5
# paginate_path:    "/blog/page:num/"
                    # Or '/blog/page:num' if you want to move your index pages







plugins_dir:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate


# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github: 
  repo:     
  - fisherra
github: [metadata]      


plugins: 
- jekyll-paginate


